name: asha_frontend
description: "ASHA Health App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # AUTH + API IMPORTANT PACKAGES
  http: ^1.2.1
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0

  # LOCAL DB (drift) already good
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.41
  sqflite: ^2.3.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.4.10
  shared_preferences: ^2.2.2


flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/hi.json
    - assets/lang/mr.json
